### ISSUE TITLE
Translation: Korean

### ISSUE THREAD

**Issue by ChialiT** [privacy-scaling-explorations/pse.dev#121]
Open for translation on the following page:
- Home page
- Project lib
- Resource
- About

How:
Navigate to https://github.com/privacy-scaling-explorations/website-v2/tree/main/app/i18n/locales
Duplicate the "en" folder for translation.

I hope this will be a group collaboration effort; if you have any questions, please leave comments.

**Comment by ChialiT** [comment]
> Hi I want to contributing Translating your page to Korean. I want to ask you into which branch from my forked repository to make PR. Do I just make PR to main branch?

Thank you so much @2ssunny 

You could just fork the main branch and submit PR to main branch too, there will be review, approval needed before merge.

**Comment by 2ssunny** [comment]
Okay I understood. I will submit PR to main branch after translating in Korea

**Comment by 2ssunny** [comment]
Check PR #148 please. If you comment what to edit, I will edit and push again.

**Comment by kalidiagne** [comment]
Closing this issue as it has now been merged. Thank you, @2ssunny @wanseob!
