### ISSUE TITLE
Translation: Japanese

### ISSUE THREAD

**Issue by ChialiT** [privacy-scaling-explorations/pse.dev#122]
Open for translation on the following page:
- Home page
- Project lib
- Resource
- About

How:
Navigate to https://github.com/privacy-scaling-explorations/website-v2/tree/main/app/i18n/locales
Duplicate the "en" folder for translation.

I hope this will be a group collaboration effort; if you have any questions, please leave comments.

**Comment by tkmct** [comment]
I can help with this effort!

**Comment by ChialiT** [comment]
yes, please @tkmct !!

**Comment by zukizukizuki** [comment]
@ChialiT @tkmct 
It looks like there is no movement and I would like to help. Is that OK?

**Comment by ChialiT** [comment]
> @ChialiT @tkmct It looks like there is no movement and I would like to help. Is that OK?

@zukizukizuki Please do, we love to have Japanese listed in our website.
you will need to fork it first then PR to the main.


Thank you so much!!!

**Comment by kalidiagne** [comment]
Closing this as it has now been merged. 
Thank you, @tkmct!
