### ISSUE TITLE
Wrong name for acceleration program

### ISSUE THREAD

**Issue by NOOMA-42** [privacy-scaling-explorations/pse.dev#178]
This should be "Acceleration program" instead of "Accelerator Program"
<img width="755" alt="截圖 2024-07-19 晚上10 16 10" src="https://github.com/user-attachments/assets/a744b2bc-585d-45c6-8f96-fa22efaa8b10">

example link: https://pse.dev/zh-TW/programs

**Comment by samajammin** [comment]
Looks like this was solved in https://github.com/privacy-scaling-explorations/pse.dev/pull/184
