### ISSUE TITLE
btw (out of scope of this PR), have you considered using an enum for this?

### ISSUE THREAD

**Issue by kalidiagne** [privacy-scaling-explorations/pse.dev#187]
btw (out of scope of this PR), have you considered using an enum for this?
```suggestion
  projectStatus: ProjectStatus.Inactive,
```

which would be defined in [`@/lib/types`](https://github.com/privacy-scaling-explorations/pse.dev/blob/05076fb21301af433bea843adfaf938b9da711af/lib/types.ts#L12-L13)

As a dev not familiar with this repo, I had to look for a project which I knew was inactive and check for its data to know what exact string to use. No big deal, but an enum would force doing the right thing automatically.

_Originally posted by @sripwoud in https://github.com/privacy-scaling-explorations/pse.dev/pull/186#discussion_r1721718778_

**Comment by samajammin** [comment]
Makes sense to me 👍

**Comment by kalidiagne** [comment]
Closing as is fixed by https://github.com/privacy-scaling-explorations/pse.dev/pull/197
