### ISSUE TITLE
Project detail pages don't display Discord/Telegram

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/pse.dev#193]
Perhaps not a bug, but I assume they should (given that info is in the project data)?

e.g. OpenPassport
<img width="568" alt="Screenshot 2024-09-18 at 22 24 39" src="https://github.com/user-attachments/assets/f6c2e54e-dd5b-4b8a-86da-b2870514e44c">

https://github.com/privacy-scaling-explorations/pse.dev/blob/main/data/projects/openpassport.ts#L13

e.g. Semaphore
<img width="651" alt="Screenshot 2024-09-18 at 22 27 04" src="https://github.com/user-attachments/assets/c8d1795a-f797-40f1-a424-9d244c90f290">

https://github.com/privacy-scaling-explorations/pse.dev/blob/main/data/projects/semaphore.ts#L14

**Comment by kalidiagne** [comment]
Closing as is fixed by https://github.com/privacy-scaling-explorations/pse.dev/pull/197
