### ISSUE TITLE
Project detail card

### ISSUE THREAD

**Issue by samajammin** [privacy-scaling-explorations/pse.dev#194]
A couple issues I noticed

1) website display

The website URL display looks a bit awkward when wrapped, e.g.
<img width="314" alt="Screenshot 2024-09-18 at 22 28 37" src="https://github.com/user-attachments/assets/72b03f64-505d-4a2c-b927-b54881018ab0">

Perhaps trim the display (to remove the `https://` & the trailing slash?)

2) built with

The "built with" tags (e.g. zk-kit circom snarkjs) seem to be clickable links but are not - what are they supposed to do? It would be cool if it linked back to the /projects page & filtered by projects w/ that tech stack 😄

**Comment by kalidiagne** [comment]
fixed here https://github.com/privacy-scaling-explorations/pse.dev/pull/197
