### ISSUE TITLE
Sidebar styling broke when headings in the project page are long

### ISSUE THREAD

**Issue by tkmct** [privacy-scaling-explorations/pse.dev#220]
I found the broken styling of the sidebar in the project page when the heading text are long
![スクリーンショット 2024-10-30 16 29 08](https://github.com/user-attachments/assets/ef9ddc94-7a2a-4485-944d-aa19fe0d904a)

**Comment by kalidiagne** [comment]
Fixed by https://github.com/privacy-scaling-explorations/pse.dev/pull/224
