### ISSUE TITLE
jubmoji card edits

### ISSUE THREAD

**Issue by rachelaux** [privacy-scaling-explorations/pse.dev#248]
- [ ] label as archived
- [ ] funding status = archived
- [ ] update image: https://www.figma.com/design/wyV1DA4B3b3v8a9grrS5Kl/%F0%9F%8C%90-PSE-Website---2023?node-id=4242-52597&node-type=frame&t=4fjXL58YfWytzgW1-11

**Comment by rachelaux** [comment]
![Project Title=Jubmoji, Version=V1 0, Size=M](https://github.com/user-attachments/assets/d0f7be17-2926-4040-83b2-12302432ae77)

**Comment by rachelaux** [comment]
- [ ] update the body copy:

Jubmoji.quest is a place to keep personal, provable digital mementos from people you meet and places you visit IRL. Each time you tap a card, you collect a Jubmoji, a unique cryptographic signature that you can store privately and share as you wish!

The learnings from this experiment influenced the creation of [Cursive](https://pse.dev/en/projects/cursive) which continues to explore applications of cryptography for human connection.

**Comment by kalidiagne** [comment]
Fixed by https://github.com/privacy-scaling-explorations/pse.dev/pull/253
