### ISSUE TITLE
nfctap.xyz card edits

### ISSUE THREAD

**Issue by rachelaux** [privacy-scaling-explorations/pse.dev#249]
**Updates**

- [ ] URL:
https://pse.dev/en/projects/cursive

- [ ] Title:
Cursive

- [ ] Description
What began as an experimental initiative to transform PSE's theoretical cryptography research into tangible applications has evolved into a dedicated lab that incubates practical ways to connect people through applied cryptography while generating valuable research feedback.
Cursive's work creates essential feedback loops between researchers and developers, continuously improving a variety of open source codebases. They've found particular success with NFC technology, which enables users to securely collect private data for cryptographic computations.
While initial experiments focused on creating engaging ways for users to gather data for zero-knowledge proofs, Cursive is now expanding into developing meaningful multiparty computation (MPC) interactions that put cutting-edge cryptographic research directly into users' hands.

- [ ] Wiki card
Project status: Active
Built with: 
Funding: Grants
Website: cursive.team

- [ ] Image:

https://www.figma.com/design/wyV1DA4B3b3v8a9grrS5Kl/%F0%9F%8C%90-PSE-Website---2023?node-id=9068-52775&node-type=frame&t=4fjXL58YfWytzgW1-11
![Cursive](https://github.com/user-attachments/assets/c9bc360c-eb20-459b-908a-7c5f4c3900b8)

**Comment by RiverRuby** [comment]
Updating description to:

What began as an experimental initiative to transform PSE's theoretical cryptography research into tangible applications has evolved into a dedicated lab that incubates practical ways to connect people through applied cryptography.

Cursive's work creates essential feedback loops between researchers and developers, continuously improving a variety of open source codebases. They also experiment with new interfaces to experience cryptography, finding particular success with NFC technology. They have used a variety of form factors like cards, stickers, and bracelets to enable users to securely collect private data for cryptographic computations. 

While initial experiments focused on creating engaging ways for users to gather data for zero-knowledge proofs, Cursive is now expanding into developing meaningful multiparty computation (MPC) interactions that put cutting-edge cryptographic research directly into users' hands.

Here are some product + research highlights:
- Client-side Nova folding to provide a "Spotify Wrapped" summary of your ZKSummit11 experience: https://github.com/cursive-team/zk-summit
- Private set intersection using multi-party FHE: https://github.com/cursive-team/2P-PSI
- Private hiring matcher using phantom-zone, a full multi-party FHE circuit builder: https://github.com/cursive-team/pz-hiring
- Trinity, a new 2PC scheme with optimal DevX and UX: https://github.com/cursive-team/trinity-v0

------

@kalidiagne this is ready to be updated!

**Comment by kalidiagne** [comment]
Fixed by https://github.com/privacy-scaling-explorations/pse.dev/pull/253
